# Generated by Django 5.2.9 on 2025-12-08 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('registered', 'Registered'), ('owner', 'Owner')], default='registered', help_text='Defines user permissions: guest, registered, or owner.', max_length=20),
        ),
    ]
