# Generated by Django 5.2.9 on 2026-05-24 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_approved',
            field=models.BooleanField(default=False, help_text='Designates whether this seller can publish listings.'),
        ),
    ]
