# Generated by Django 5.2.9 on 2025-12-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
